# Generated by Django 4.0.3 on 2022-05-10 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0004_alter_yangiliklar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='yangiliklar',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
