# Generated by Django 4.0.3 on 2022-05-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_yangiliklar_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yangiliklar',
            name='likes',
        ),
        migrations.AddField(
            model_name='yangiliklar',
            name='dislike_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
